#!/usr/bin/python

import sys, os

pid = sys.argv[1]
data = open('/proc/%s/io' % pid, 'r').read()

lines = data.split('\n')
lines = [line.split(':') for line in lines if line]
lines = dict([(name, float(val)/1024/1024) for name, val in lines])

print 'PID =', pid
print 'Bytes read         = %0.3f MB' % lines['rchar']
print 'Bytes really read  = %0.3f MB' % lines['read_bytes']
print 'Bytes wrote        = %0.3f MB' % lines['wchar']
print 'Bytes really wrote = %0.3f MB' % lines['write_bytes']
