#!/usr/bin/python

import sys, os

if len(sys.argv) < 4:
    print('''rename the files
    python rename.py old new files(wildcard)

    {old} in the file names will be replace by {new}.

    for old, '--s' matches the start, '--e' matches the end.
    if old="-", then just list the files
    if new="-", then just remove the substring
    ''')
    sys.exit(1)

old, new = sys.argv[1:3]
files = sys.argv[3:]

if old == '-': 
    old = ''
if new == '-': 
    new = ''

tasks = []
for file in files:
    path, fname = os.path.split(file)
    if path: path = '/' + path

    new_file = None
    if old == '--s':
        tasks.append((file, path + new + fname))
    elif old == '--e':
        tasks.append((file, path + fname + new))
    elif fname.find(old) >= 0:
        tasks.append((file, path + fname.replace(old, new)))

for task in tasks:
    print "%s -> %s" % task
print "%d files to be renamed." % len(tasks)

ans = raw_input('Execute? ')
if ans.lower().startswith('y'):
    os.rename(file, new_file)
    print 'Done.'
else:
    print 'Cancelled.'
